# Generated by Django 5.0.3 on 2026-02-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps_wood_app', '0004_cart_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Card Payment')], default='cod', max_length=20),
        ),
    ]
