# Generated by Django 5.0.3 on 2026-02-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps_wood_app', '0006_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revoked', 'Revoked')], default='pending', max_length=20),
        ),
    ]
