# Generated by Django 5.0.3 on 2026-02-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps_wood_app', '0007_owner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('block', 'Block'), ('unblock', 'Unblock')], default='unblock', max_length=20),
        ),
    ]
