# Generated by Django 5.0.3 on 2026-03-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps_wood_app', '0008_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='type',
            field=models.CharField(default='owner', max_length=50),
        ),
    ]
